### ISSUE TITLE
Number primitive has more than 15 significant digits

### ISSUE THREAD

**Issue by tomkha** [WebDollar/Node-WebDollar#168]
```
0|WebD     |  ⚠   ---------------------------------------------------------------------------- 
0|WebD     |  ⚠   WebDollar Block was mined  286853  nonce ( 2151404650) 00000000519de640197b339687e4db296ee5efc6ca5b3d588aeb1d68d3b59b7b  reward 6000 WEBD 3564a019aaf0306d5b5a76d9251cec8e84604d33 
0|WebD     |  ⚠   ---------------------------------------------------------------------------- 
0|WebD     |  ✘   MiniBlockchain simulateNewBlock 1 raised an exception at blockHeight 286853 Error: [BigNumber Error] Number primitive has more than 15 significant digits: 336.34999999962747
0|WebD     |     at new BigNumber (/home/ubuntu/webdollar/node_modules/bignumber.js/bignumber.js:312:27)
0|WebD     |     at BigNumber.P.dividedToIntegerBy.P.idiv (/home/ubuntu/webdollar/node_modules/bignumber.js/bignumber.js:1569:31)
0|WebD     |     at InterfaceBlockchainBlocks.recalculateNetworkHashRate (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:23388:30)
0|WebD     |     at MainBlockchain._onBlockCreated (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:14184:25)
0|WebD     |     at MainBlockchain._onBlockCreated (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:13653:107)
0|WebD     |     at MainBlockchain.includeBlockchainBlock (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:14163:20)
0|WebD     |     at <anonymous> { height: 286853,
```

**Comment by ibudisteanu** [comment]
This could be the reason why in browser very rarely it shows the network hashrate negative, but unfortunately I am not able to spot the error. 

It looks like the error is generated at the following line:

`let answer = SumDiff.dividedToIntegerBy(how_much_it_took_to_mine_X_Blocks).toNumber();`

![image](https://user-images.githubusercontent.com/17750489/45899863-bb75fe00-bde6-11e8-87a6-21d2ea82e611.png)

**Comment by ibudisteanu** [comment]
I did a minor review, but it won't solve that issue https://github.com/WebDollar/Node-WebDollar/commit/f9f69c514be4dc956b3be7037501ec2f8043dc42

**Comment by ibudisteanu** [comment]
Probably the issue was fixed https://github.com/WebDollar/Node-WebDollar/commit/3f393cca679e941f892caf73d54ee4a10f937482
