### ISSUE TITLE
 Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by tomkha** [WebDollar/Node-WebDollar#170]
```
0|WebD     |  ✘   ERROR serializing block:  TypeError: Cannot read property 'length' of undefined
0|WebD     |     at MiniBlockchainTransactionFrom.serializeFrom (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:15429:132)
0|WebD     |     at MiniBlockchainTransaction._serializeTransaction (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:10001:23)
0|WebD     |     at MiniBlockchainTransaction.serializeTransaction (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:9982:21)
0|WebD     |     at InterfaceBlockchainBlockDataTransactions.serializeTransactions (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:23542:48)
0|WebD     |     at MiniBlockchainBlockData._computeBlockDataHeaderPrefix (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:10574:31)
0|WebD     |     at MiniBlockchainBlockData._computeBlockDataHeaderPrefix (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:27340:74)
0|WebD     |     at MiniBlockchainBlockData.serializeData (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:10589:18)
0|WebD     |     at MiniBlockchainBlock._computeBlockHeaderPrefix (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:6070:64)
0|WebD     |     at MiniBlockchainBlock._computeBlockHeaderPrefix (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:27025:171)
0|WebD     |     at MiniBlockchainBlock.serializeBlock (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:6138:14) 
```

**Comment by ibudisteanu** [comment]
was fixed in the laster master2 commit. Let me know if you encounter the issue anymore.
