### ISSUE TITLE
Cannot read property 'length' of undefined at MiniBlockchainTransactionFrom.calculateInputSum

### ISSUE THREAD

**Issue by tomkha** [WebDollar/Node-WebDollar#172]
this prevents miner from swtiching to the outer fork

```
0|WebD     | TypeError: Cannot read property 'length' of undefined
0|WebD     |     at MiniBlockchainTransactionFrom.calculateInputSum (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:15350:44)
0|WebD     |     at MiniBlockchainTransaction._processTransactionFees (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:9666:34)
0|WebD     |     at MiniBlockchainTransaction.processTransaction (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:10097:22)
0|WebD     |     at MiniBlockchainFork.preFork (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:12373:57)
0|WebD     |     at Object.success.blockchain.semaphoreProcessing.processSempahoreCallback [as callback] (/home/ubuntu/webdollar/dist_bundle/terminal-bundle.js:6786:26)
0|WebD     |     at <anonymous>
0|WebD     |     at process._tickCallback (internal/process/next_tick.js:188:7)
0|WebD     | blockchainForks  preFork raised an error 
```

**Comment by ibudisteanu** [comment]
Most probably was solved. This is due to the fact the transaction was deleted in the mean while

**Comment by ibudisteanu** [comment]
was fixed in the laster master2 commit. Let me know if you encounter the issue anymore.
