### ISSUE TITLE
Nonce is not right 2

### ISSUE THREAD

**Issue by craveica** [WebDollar/Node-WebDollar#287]
What does this mean?
```
 ⚠   Error Including Transaction { message: 'Nonce is not right 2',
  myNonce: 3,
  nonce: null,
  txId: '4301b0b2d2d2be1e7bedc4fce6d9ca0e2ac82ee7e15359d0969e2d1d4bed0f49' } 
 ⚠   Error Including Transaction TypeError: Cannot read property 'node' of undefined
    at Function.broadcastRequest (/home/webd/MiningPool1/dist_bundle/terminal-menu-bundle.js:6663:40)
    at InterfaceBlockchainTransactionsProtocol.propagateNewMissingNonce (/home/webd/MiningPool1/dist_bundle/terminal-menu-bundle.js:24454:110)
    at TransactionsPendingQueue.propagateMissingNonce (/home/webd/MiningPool1/dist_bundle/terminal-menu-bundle.js:24161:39)
    at MiningTransactionsSelector.selectNextTransactions (/home/webd/MiningPool1/dist_bundle/terminal-menu-bundle.js:31600:79)
    at <anonymous> 
4301b0b2d2d2be1e7bedc4fce6d9ca0e2ac82ee7e15359d0969e2d1d4bed0f49 WEBD$gC4vLB$Y0S0KrBCUMhqbot10$27xi46dqz$
4301b0b2d2d2be1e7bedc4fce6d9ca0e2ac82ee7e15359d0969e2d1d4bed0f49 ------- GOOD tx
```

**Comment by ibudisteanu** [comment]
This error message is shown when you have multiple transactions but one is missing.

**Comment by craveica** [comment]
That makes sense. Thank you.
